package de.tebbeubben.remora.lib.util

import dagger.Reusable
import javax.inject.Inject

@Reusable
internal class VerificationString @Inject constructor() {

    fun getVerificationWords(verificationData: ByteArray): List<String> =
        verificationData.map { WORD_LIST[it.toInt() and 0x0F] }

    companion object {
        val WORD_LIST = """
            bolus
            basal
            carbs
            insulin
            dose
            correction
            prebolus
            IOB
            ratio
            sensitivity
            target
            hypo
            hyper
            range
            time-in-range
            glucose
            ketone
            unit
            site
            rotation
            dosing
            snack
            meal
            fiber
            hydration
            activity
            exercise
            movement
            sleep
            rest
            pump
            sensor
            infusion
            cannula
            reservoir
            tubing
            clip
            adhesive
            patch
            reader
            transmitter
            pod
            charger
            receiver
            alert
            alarm
            buzzer
            display
            trend
            arrow
            graph
            logbook
            strip
            lancet
            meter
            lancing
            case
            pouch
            data
            upload
            banting
            best
            macleod
            collip
            langerhans
            minkowski
            von-maring
            paulescu
            allen
            joslin
            georg-zuelzer
            inslet
            pancreas
            beta-cell
            islet
            hormone
            glucagon
            peptide
            receptor
            biosynthesis
            awareness
            stigma
            inclusion
            diversity
            equity
            accessibility
            solidarity
            empowerment
            advocacy
            support
            peer
            friendship
            ally
            representation
            acceptance
            visibility
            storytelling
            connection
            kindness
            generosity
            patience
            openness
            curiosity
            sharing
            collaboration
            listening
            encouragement
            participation
            respect
            nightscout
            androidaps
            openaps
            loop
            wearenotwaiting
            xdrip
            tidepool
            aaps
            libretools
            openhumans
            openwearables
            artificial-pancreas
            community-code
            github
            fork
            merge
            commit
            branch
            release
            contributor
            maintainer
            documentation
            pull-request
            issue
            bugfix
            test
            prototype
            firmware
            hardware
            blueprint
            circle
            blue
            november
            unity
            hope
            light
            glow
            ribbon
            globe
            heartbeat
            wave
            drop
            cloud
            sunrise
            horizon
            path
            bridge
            journey
            constellation
            spark
            lantern
            star
            candle
            flame
            sky
            ocean
            river
            rain
            snow
            wind
            joy
            calm
            peace
            trust
            pride
            gratitude
            excitement
            motivation
            inspiration
            strength
            courage
            resilience
            focus
            balance
            harmony
            energy
            vitality
            warmth
            laughter
            comfort
            relief
            flow
            ease
            clarity
            freedom
            belonging
            togetherness
            mindfulness
            creativity
            growth
            access
            consent
            education
            rights
            literacy
            transparency
            privacy
            justice
            safety
            compassion
            allyship
            community
            outreach
            activism
            prevention
            dignity
            fairness
            dialogue
            agency
            engagement
            cooperation
            equality
            tolerance
            integrity
            inclusionary
            voice
            mentorship
            leadership
            innovation
            stewardship
            guidance
            empathy
            care
            bolusing
            looping
            patching
            trending
            syncing
            calibrate
            ratioing
            alerting
            beacon
            ripple
            glycemia
            isletology
            endocrinology
            biosensor
            telehealth
            carbcounting
            microbolus
            microdose
            dexterity
            infusionist
            diabetology
            glycation
            loopable
            humanness
        """.trimIndent().lines()
    }
}